version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    versioning-strategy: increase
    ignore:
      - dependency-name: sass-loader
        versions:
          - ">= 8.a, < 9"
      - dependency-name: ts-loader
        versions:
          - ">= 9.a, < 10"
      - dependency-name: "webpack"
        versions:
          - ">= 5.a, < 6"
      - dependency-name: "@types/webpack"
        versions:
          - ">= 5.a, < 6"
