version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: css-loader
    versions:
    - ">= 2.a, < 3"
  - dependency-name: css-loader
    versions:
    - ">= 3.a, < 4"
  - dependency-name: sass-loader
    versions:
    - ">= 8.a, < 9"
  - dependency-name: ts-loader
    versions:
    - 9.0.2
  - dependency-name: css-loader
    versions:
    - 5.2.2
  - dependency-name: "@types/webpack-bundle-analyzer"
    versions:
    - 3.9.2
  - dependency-name: "@types/webpack"
    versions:
    - 5.0.0
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.2
  - dependency-name: "@sudoo/triforce"
    versions:
    - 2.9.14
