version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    versioning-strategy: increase
    ignore:
      - dependency-name: css-loader
        versions:
          - ">= 2.a, < 3"
      - dependency-name: css-loader
        versions:
          - ">= 3.a, < 4"
      - dependency-name: sass-loader
        versions:
          - ">= 8.a, < 9"
      - dependency-name: "@types/webpack"
        versions:
          - ">= 5.a, < 10"
